name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [14, 20, 22]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 24
            operating-system: [ubuntu-latest]
        exclude:
          - node-version: 14
            operating-system: windows-latest
    runs-on: ${{matrix.operating-system}}
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install nodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependecies
        run: npm ci
      - name: Build project
        run: npm run build
